data:
  query_file_paths:
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_category.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_instruction.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G1_tool.json"
  fine_tuning_query_file_paths:
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G2_category.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G2_instruction.json"
    - "https://raw.githubusercontent.com/THUNLP-MT/StableToolBench/refs/heads/master/solvable_queries/test_instruction/G3_instruction.json"
  tool_file_paths:
    - "https://huggingface.co/datasets/stabletoolbench/ToolEnv2404/resolve/main/toolenv2404_filtered.tar.gz"
  reference_answers_path: "https://huggingface.co/datasets/stabletoolbench/baselines/resolve/main/data_baselines.zip"
  reference_model_id: "chatgpt_cot"
  queries_num: 5  # Small number for quick testing; increase for full evaluation

models:
  - id: "Qwen/Qwen3-8B"
    url: "${QWEN_MODEL_URL}"
    provider_id: "vllm"

environments:
  - model_id: "Qwen/Qwen3-8B"
    irrelevant_tools_ratio: 0.0
    irrelevant_tools_from_same_categories: true

algorithms:
  - label: "Tool Fetcher"
    module_name: "tool_fetcher"
    settings:
      # Dense embedding model for indexing tools (same as tool_rag for fair comparison)
      embedding_model_id: "all-MiniLM-L6-v2"
      # Default k used when the LLM calls tool_hub search without specifying k
      default_search_k: 8
      # Max characters returned from tool invocations (prevents context overflow)
      max_result_chars: 4000
      # Note: drop_old_collection and collection_name omitted (using defaults)

metric_collectors:
  - module_name: "tool_selection_metric_collector"
    settings: {}
  - module_name: "tool_retrieval_metric_collector"
    settings:
      ks: [1, 3]
      ap_rel_threshold: 1.0
  - module_name: "efficiency_metric_collector"
    settings: {}


